apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service1-deployment
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
